version: '3.7'
services:
  database:
    image: postgres:15-alpine
    container_name: brain_agriculture_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs_app:
    build: .
    container_name: brain_agriculture_nestjs
    restart: always
    depends_on:
      - database
    ports:
      - '${APP_PORT}:3000'
    env_file:
      - .env

volumes:
  postgres_data:
